name: On Cron
on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  tests:
    permissions:
      contents: read
      pull-requests: read
      checks: write
    uses: ./.github/workflows/tests.yaml

  hacs:
    permissions:
      contents: read
      pull-requests: read
      checks: write
    uses: ./.github/workflows/hacs.yaml