name: Run Tests
on:
  workflow_call:

jobs:
  ruff:
    name: Ruff checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ruff
        uses: astral-sh/ruff-action@v3

      - name: Run Ruff
        run: ruff check --output-format=github .


  codespell:
    name: Run Codespell

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: ./.*,*.csv,*.json
          ignore_words_list: hass,alot,datas,dof,dur,farenheit,hist,iff,ines,ist,lightsensor,mut,nd,pres,referer,ser,serie,te,technik,ue,uint,visability,wan,wanna,withing

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.test.txt
          pip install pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=custom_components/gatus_ha tests/

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2